environment: development

apphost: k8s

label:
  name: test

container:
  name: testcontainer
  image: testtask
  pullPolicy: IfNotPresent
  tag: v1
  port: 80
replicas: 1

service:
  port: 8888
  type: ClusterIP